### ISSUE TITLE
Populating List Cards with List Items Count

### ISSUE THREAD

**Issue by suzypowers** [devhausleipzig/camp8-final-project#112]
Have [List Cards](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=76%3A429&t=MNvp1b0AO9S6O4d3-4) properly reflect the number of items within them.

The [cards](https://github.com/devhausleipzig/camp8-final-project/pull/49) and [count](https://github.com/devhausleipzig/camp8-final-project/issues/105) have already been built, they only need connecting.

**Comment by amyria3** [comment]
Eru already did
