### ISSUE TITLE
Three button components could be refactored into a single one / use CVA in application

### ISSUE THREAD

**Issue by franzwollang** [devhausleipzig/camp8-final-project#128]
The button components:
- IconButton
- LargeButton
- PlusButton

Could easily be refactored into a single button with some props to control different aspects of style and functionality. In fact, 'LargeButton' already has some of this abstraction and could serve as the basis for merging all of them together.

The only button component that seems be unique and unmergeable with the others is 'SortByButton', since it is a tab list and not a button. However, elements of the tab list are button-like. In order to enforce consistent design, you may want to have those button-like elements of the tab list share styling with your buttons.

Defining a [CVA](https://cva.style/docs) object inside your button component to manage the styling variants and importing it into the 'SortByButton' component would allow maintainable sharing of styling between your buttons and the button-like aspects of the tab list. CVA could also be very helpful if used across the entire application. Please consider this proposal.

**Comment by suzypowers** [comment]
Students agreed that this wasn't something they wanted to pursue.
