### ISSUE TITLE
Login Screens

### ISSUE THREAD

**Issue by suzypowers** [devhausleipzig/camp8-final-project#141]
This page appears after pressing "get started" on the splash page. After inputting your email you are presented with a "get link" button which sends a link to your email address. 

- [ ] Type in Email (any text '@' any text '.com') 
- [ ] Get Link Button Appears
- [ ] Login with Google
- [ ] "Link sent to email" Screen

**Comment by ArthiRagothaman** [comment]
Login screens is working as expected.
