### ISSUE TITLE
Component / Primary Button

### ISSUE THREAD

**Issue by suzypowers** [devhausleipzig/camp8-final-project#33]
The primary button used throughout the app. Found in [splash page](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=179%3A284&t=VFP4EsWJjjsX3gCT-4), [login/signup](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=554%3A3833&t=VFP4EsWJjjsX3gCT-4), and [account/settings](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=284%3A1629&t=VFP4EsWJjjsX3gCT-4)

**Comment by acz1992** [comment]
guys I think that this is a duplicate of Large Button which has now been sent for review (and includes also secondary button)
