### ISSUE TITLE
Implement Swipe to Delete Component and Undo

### ISSUE THREAD

**Issue by suzypowers** [devhausleipzig/camp8-final-project#96]
- [ ] style according to [mockup](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=645%3A3786&t=VFP4EsWJjjsX3gCT-4)
- [ ] swipe left to [delete ](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=645%3A3735&t=VFP4EsWJjjsX3gCT-4)
- [ ] [snaps back](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=386%3A2744&t=VFP4EsWJjjsX3gCT-4) when released 1/3 of the way through swipe
- [ ] create [undo option](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=688%3A6064&t=VFP4EsWJjjsX3gCT-4) with prompt

**Comment by iameru** [comment]
did this here for the card: https://github.com/devhausleipzig/camp8-final-project/pull/49#issuecomment-1451629978
and william did swipe actions for list items aswell. 
we used 50% and not 33.3% 
@TheDoplarEffect
